### ISSUE TITLE
Server-Side Handler

### ISSUE THREAD

**Issue by ske42** [ske42/Profile#4]
PHP file 
MUST DO
- [ ] ecronize spec-simboles 
- [ ] autorized???
- [ ] Get POST-requst from #1 
**if requst for reading**
- [ ]  Send Data for User whose UID sent in #1 request

**If request for add**
- [ ] Send Json string without "whatToDo" var to Inner method #5

**If request for change**
- [ ] Send Json string without "whatToDo" var to Channger method #5

**If request for deliting**
- [ ] Send UID to Delete method
